### PR TITLE
Added CU for July and August

### PR DESCRIPTION
**Pull request by andreasblueher**
I'll try to add some of the other ones aswell

### CODE REVIEW

**Comment by andreasblueher** [comment]
@brianlala I've tested SP2016 and SP2019 and both worked

**Comment by brianlala** [comment]
My apologies! I merged a later PR that had similar changes and missed yours. Appreciate your contributions and will be quicker to respond next time :\

**Comment by andreasblueher** [comment]
hey @brianlala I had send an email to you regarding the pull request and maintainment of these repositories. Did you get it? Cheers. No worries

**Comment by brianlala** [comment]
Yes, I replied on Aug 25, did you not get the reply?

**Comment by brianlala** [comment]
And apologies once again for missing this PR.

**Comment by andreasblueher** [comment]
No i did not receive an email back. I checked my spam folder, but i've been clearing it on a regular basis so there is nothing from August left. Could you resend that email please? Thank you

**Comment by brianlala** [comment]
Just re-sent to your gmail address.

**Pull request closed without merging**
